config/routes.rb
Ninjanews::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users, except: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  
  resources :feeds, :sources, :interest_questions

end

app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id              :integer         not null, primary key
#  source_id       :integer
#  url             :string(255)
#  section         :string(255)
#  area_importance :integer
#  is_local_news   :boolean         default(FALSE)
#  created_at      :datetime
#  updated_at      :datetime
#

class Feed < ActiveRecord::Base
  validates :source, presence: true
  validates :section, presence: true
  validates :url, presence: true, uniqueness: true

  belongs_to :source
  has_many :relation_levels, dependent: :destroy
  has_many :interest_questions, through: :relation_levels
  has_many :articles, dependent: :destroy
  has_many :feed_scores, dependent: :destroy

  accepts_nested_attributes_for :relation_levels
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def new
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @feed = Feed.new
    @sources = Source.all
    @interest_questions = InterestQuestion.all
    InterestQuestion.all.each do |iq|
      @feed.relation_levels.find_or_initialize_by(interest_question_id: iq.id)
    end
  end

  def create
    return unless current_user.is_admin
    @feed = Feed.new(feed_params)
    if @feed.save
      redirect_to '/feeds', notice: 'Feed created.'
    else
      render action: 'new'
    end
  end

  def edit
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @feed = Feed.find(params[:id])
    @sources = Source.all
    @interest_questions = InterestQuestion.all
    InterestQuestion.all.each do |iq|
      @feed.relation_levels.find_or_initialize_by(interest_question_id: iq.id)
    end
  end

  def update
    return unless current_user.is_admin
    @interest_questions = InterestQuestion.all
    @feed = Feed.find(params[:id])
    if @feed.update_attributes(feed_params)
      redirect_to :back, notice: 'Feed updated.'
    else
      render action: 'new'
    end
  end

  def destroy
    return unless current_user.is_admin
    Feed.find(params[:id]).destroy
    redirect_to feeds_path, notice: 'Feed destroyed.'
  end

  def index
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @feeds = Feed.all
  end

  private

    def feed_params
      params.require(:feed).permit(:url, :source_id, :section, 
                                   :area_importance, :is_local_news, 
                                   relation_levels_attributes: 
                                   [:interest_question_id, :score, :feed_id])
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.haml
.form.admin-text.container
  =semantic_form_for(@feed) do |f|
    -if @feed.errors.any?
      #error_explaination
        %h2
          =pluralize(@feed.errors.count, 'error')
        %ul
          -@feed.errors.full_messages.each do |msg|
            %li=msg
            
    =f.inputs do
      =f.inputs :url, :section, :is_local_news, :area_importance

      =f.collection_select :source_id, @sources, :id, :title

      =f.inputs for: :relation_levels do |rl, i|
        =rl.label @interest_questions[i-1].question_text
        =rl.range_field :score, max: 100, min: 0

        =rl.hidden_field :interest_question_id, value: @interest_questions[i-1].id

    =f.submit class: 'btn btn-large btn-primary'

app/views/feeds/edit.html.haml
-if current_user.is_admin
  -provide :title, 'Edit Feed'
  %h1 Edit Feed

  =render 'form'

-else
  %h1 ACCESS DENIED

app/views/feeds/index.html.haml
-if current_user.is_admin
  -provide :title, 'All Feeds'
  %h1 All Feeds
  %p.admin-text= link_to 'Create a new feed', new_feed_path
  %ul
    -@feeds.each do |feed|
      %li.admin-text
        = link_to "#{feed.section}, #{feed.source.title}", feed.url
        = "-----"
        = link_to 'Edit', edit_feed_path(feed)
        = "-----"
        = link_to 'Delete', feed_path(feed), method: :delete
-else
  %h1 ACCESS DENIED
  

app/views/feeds/new.html.haml
-if current_user.is_admin
  -provide :title, 'New Feed'
  %h1 New Feed

  =render 'form'

-else
  %h1 ACCESS DENIED