config/routes.rb
Ninjanews::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users, except: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  
  resources :feeds, :sources, :interest_questions

end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id           :integer         not null, primary key
#  title        :string(255)
#  url          :string(255)
#  area         :string(255)
#  published_at :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

class Source < ActiveRecord::Base
  validates :title, :url, presence: true
  validates :url, uniqueness: true

  has_many :feeds
  has_many :articles, through: :feeds
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def new
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @source = Source.new
    @feeds = Feed.all
  end

  def create
    return unless current_user.is_admin
    @source = Source.new(source_params)
    if @source.save
      redirect_to :back, notice: "Source (#{@source.title} created."
    else
      render action: 'new'
    end
  end

  def edit
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @source = Source.find(params[:id])
  end

  def update
    return unless current_user.is_admin
    @source = Source.find(params[:id])
    if @source.update_attributes(source_params)
      redirect_to :back, notice: 'Source updated.'
    else
      render action: 'new'
    end
  end

  def index
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @sources = Source.all
  end

  def destroy
    return unless current_user.is_admin
    Source.find(params[:id]).destroy
    redirect_to sources_path, notice: 'Source destroyed.'
  end

  private

    def source_params
      params.require(:source).permit(:title, :url, :area)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.haml
.form.admin-text
  =semantic_form_for(@source) do |f|
    -if @source.errors.any?
      #error_explaination
        %h2
          =pluralize(@source.errors.count, 'error')
        %ul
          -@source.errors.full_messages.each do |msg|
            %li=msg

    =f.inputs do
      =f.input :title
      =f.input :url
      =f.input :area

    =f.actions do
      =f.action :submit
      =f.action :cancel

app/views/sources/edit.html.haml
-if current_user.is_admin
  -provide :title, 'Edit Source'
  %h1 Edit Source

  =render 'form'
-else
  %h1 ACCESS DENIED

app/views/sources/index.html.haml
-if current_user.is_admin
  -provide :title, 'All Sources'
  %h1 All Sources
  %p.admin-text= link_to 'New Source', new_source_path
  %ul
    -@sources.each do |source|
      %li.admin-text
        = source.title
        =', '
        = link_to source.url, source.url
        = "----"
        = link_to 'Edit', edit_source_path(source)
        = "----"
        = link_to 'Delete', source_path(source), method: 'delete'
-else
  %h1 ACCESS DENIED

app/views/sources/new.html.haml
-if current_user.is_admin
  -provide :title, 'New Source'
  %h1 New Source

  =render 'form'
-else
  %h1 ACCESS DENIED