config/routes.rb
Ninjanews::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users, except: [:new, :create]
  resources :sessions, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  
  resources :feeds, :sources, :interest_questions

end

app/models/interest_question.rb
# == Schema Information
#
# Table name: interest_questions
#
#  id            :integer         not null, primary key
#  question_text :text
#  created_at    :datetime
#  updated_at    :datetime
#

class InterestQuestion < ActiveRecord::Base
  validates :question_text, presence: true
  has_many :relation_levels, dependent: :destroy
  has_many :interest_answers, dependent: :destroy
end

app/controllers/interest_questions_controller.rb
class InterestQuestionsController < ApplicationController
  def new
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @interest_question = InterestQuestion.new
  end

  def create
    return unless current_user.is_admin
    @interest_question = InterestQuestion.new(interest_question_params)
    if @interest_question.save
      redirect_to :back, notice: 'Interest question created.'
    else
      render action: 'new'
    end
  end

  def edit
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @interest_question = InterestQuestion.find(params[:id])
  end

  def update
    return unless current_user.is_admin
    @interest_question = InterestQuestion.find(params[:id])
    if interest_question.update_attributes(interest_question_params)
      redirect_to :back, notice: 'Interest question updated.'
    else
      render action: 'edit'
    end
  end

  def index
    unless current_user && current_user.is_admin
      redirect_to signin_path
      return
    end
    @interest_questions = InterestQuestion.all
  end

  def destroy
    return unless current_user.is_admin
    InterestQuestion.find(params[:id]).destroy
    redirect_to interest_questions_path, notice: 'Interest question destroyed.'
  end

  private

    def interest_question_params
      params.require(:interest_question).permit(:question_text)
    end
end

app/helpers/interest_questions_helper.rb
module InterestQuestionsHelper
end

app/views/interest_questions/_form.html.haml
.form.admin-text
  =semantic_form_for(@interest_question) do |f|
    -if @interest_question.errors.any?
      #error_explaination
        %h2
          =pluralize(@interest_question.errors.count, 'error')
        %ul
          -@interest_question.errors.full_messages.each do |msg|
            %li=msg
    =f.inputs do
      =f.input :question_text, as: :text
    =f.actions do
      =f.action :submit
      =f.action :cancel

app/views/interest_questions/edit.html.haml
-if current_user.is_admin
  -provide :title, 'Edit Interest Question'
  %h1 Edit Interest Question
  =render 'form'
-else
  %h1 ACCESS DENIED

app/views/interest_questions/index.html.haml
-if current_user.is_admin
  -provide :title, 'All Interest Questions'
  %h1 All Interest Questions
  %p.admin-text= link_to 'New Interest Question', new_interest_question_path
  %ul
    -@interest_questions.each do |iq|
      %li.admin-text
        =link_to iq.question_text, edit_interest_question_path(iq)
        ='----'
        =link_to 'Delete', interest_question_path(iq), method: 'delete'
-else
  %h1 ACCESS DENIED

app/views/interest_questions/new.html.haml
-if current_user.is_admin
  -provide :title, 'New Interest Question'
  %h1 New Interest Question
  =render 'form'
-else
  %h1 ACCESS DENIED